// Generated by CoffeeScript 1.7.1
var getRecipes, recipeAjaxd;

recipeAjaxd = 0;

$(document).ready(function() {
  addInfiniteScroll($('#main_Browse_Recipe'), 1000, function() {
    if ($('#main_Browse_Recipe').find("Results").hasClass("hidden")) {
      search(window.query, searchAjaxd);
    } else {
      getRecipes(recipeAjaxd);
    }
  });
});

getRecipes = function(times) {
  $.ajax({
    type: "GET",
    url: 'http://54.178.135.71:8080/CookIEServer/discover_recipes',
    dataType: 'application/json',
    data: {
      'type': 'popular',
      'times': times
    },
    timeout: 10000,
    success: function(data) {
      var scope;
      data = JSON.parse(data);
      console.log("[SUCCESS]fetch recipes");
      console.log(data);
      recipeAjaxd++;
      $('#main_Browse_Recipe').scroller().clearInfinite();
      if (data.length === 0) {
        $("#main_Browse_Recipe").find("#infinite").text("No more recipes");
        recipeAjaxd--;
        return;
      }
      scope = $("#main_Browse_Recipe");
      appendRecipeResult(scope, data);
    },
    error: function(resp) {
      console.log("[ERROR]fetch recipes");
      console.log(resp);
      if (resp.status === 0) {
        $("#main_Browse_Recipe").find("#infinite").text("Server Error. Try again later.");
      } else {
        $("#main_Browse_Recipe").find("#infinite").text("Connection Error: " + resp.status);
      }
      $('#main_Browse_Recipe').scroller().clearInfinite();
    }
  });
};
