// Generated by CoffeeScript 1.7.1
var getIngredientList, moveCheckedIngredientToBottom, reloadToBuyList, showIngredientList, storeIngredientListToDB;

getIngredientList = function(recipeIds) {
  var data, id, _i, _len;
  console.log("get ingredient list");
  $.ui.blockUI(0.1);
  $.ui.showMask("Updating...");
  data = '';
  for (_i = 0, _len = recipeIds.length; _i < _len; _i++) {
    id = recipeIds[_i];
    data += 'recipes=' + id + '&';
  }
  $.ajax({
    type: 'GET',
    url: 'http://54.178.135.71:8080/CookIEServer/list_ingredient?' + data,
    timeout: 10000,
    success: function(data) {
      data = JSON.parse(data);
      console.log('[SUCCESS] fetching #' + recipeIds);
      console.log(data);
      storeIngredientListToDB(data);
      showIngredientList();
    },
    error: function(data, status) {
      console.log('[ERROR] fetching #' + recipeIds);
      console.log(data);
    }
  });
};

storeIngredientListToDB = function(data) {
  var ingredient, _i, _len;
  console.log("store ingredient list to db");
  db.transaction(function(transaction) {
    transaction.executeSql('DELETE FROM `MenuIngredients`', [], successCallBack, errorHandler, errorHandler, nullHandler);
  });
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    ingredient = data[_i];
    AddValueToIngredient(ingredient.ingredientId, ingredient.recipeId, ingredient.ingredientName, ingredient.amount, ingredient.unitName);
  }
};

showIngredientList = function() {
  if (!window.openDatabase) {
    alert('Databases not supported by this browser');
    return;
  }
  console.log("show ingredient list");
  $("#EmptyNotify").removeClass('hidden');
  $("#ToBuyListCookBtn").addClass('hidden');
  db.transaction(function(transaction) {
    transaction.executeSql('SELECT * FROM MenuIngredients', [], function(transaction, result) {
      var html, i, list, row, x, _i, _len, _ref;
      if ((result != null) && (result.rows != null)) {

        /* if there's no list in the DB */
        if (result.rows.length === 0) {
          return;
        }

        /* there's list in the DB */
        list = $("#list");
        list.html("");
        html = '';
        _ref = result.rows;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          x = _ref[i];
          row = result.rows.item(i);
          html += '<li class="listEle">' + row.name + '&nbsp;' + row.amount + '&nbsp;' + row.unitName + '</li>';
        }
        list.append(html);
        $('.listEle').click(function(event) {
          if ($(this).css('textDecoration') === 'line-through') {
            $(this).css('textDecoration', 'none');
            $(this).css('color', '#53575E');
            $(this).removeClass('list-selected');
            $(this).removeClass('not-moved');
          } else {
            $(this).css('textDecoration', 'line-through');
            $(this).css('color', '#D8D8D8');
            $(this).addClass('list-selected');
            $(this).addClass('not-moved');
          }
          clearTimeout(window.lastId);
          window.lastId = setTimeout(function() {
            return moveCheckedIngredientToBottom();
          }, 2000);
        });
        $("#EmptyNotify").addClass('hidden');
        $("#ToBuyListCookBtn").removeClass('hidden');
        $.ui.hideMask();
        $.ui.unblockUI();
      }
    }, errorHandler, errorHandler, nullHandler);
  });
};

moveCheckedIngredientToBottom = function() {
  console.log("move checked to bottom");
  $('#list').find('.not-moved').forEach(function(listEle) {
    var ele, html;
    html = listEle.outerHTML;
    ele = $(listEle);
    return ele.css3Animate({
      opacity: '0.1',
      time: '200ms',
      success: function() {
        ele.removeClass('not-moved');
        ele.remove();
        return $('#list').append(html);
      }
    });
  });
};

reloadToBuyList = function() {
  console.log("reload to buy list");
  if (!window.deckChanged) {
    return;
  }
  if (window.recipesInDeck.length === 0) {
    $("#list").html("");
    $("#EmptyNotify").removeClass('hidden');
    $("#ToBuyListCookBtn").addClass('hidden');
    return;
  }
  getIngredientList(window.recipesInDeck);
  window.deckChanged = false;
};
